version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
